### ISSUE TITLE
Error: Multibeam buffer is smaller than requested size

### ISSUE THREAD

**Issue by KevinKW87** [noaa-ocs-hydrography/kluster#118]
New user here. Found the project while looking for an alternative to MB-System. Much better UI!

I am working with the .s7k files from NOAA Survey H11984. I had to rename ".S7K" to lowercase ".s7k" and then they could open.

When I attempted to process, I got the error as shown in the screenshot below.

My contact is kevin.klemens@endurancemarineexploration.com if this is a "me" error and not a software one.

![MB Buffer Error](https://github.com/noaa-ocs-hydrography/kluster/assets/9004033/04d7bab3-cfb4-4803-ab2d-3847243b2bff)

**Comment by ericgyounkin** [comment]
Hi Kevin, not sure at first glance, looks like there might be a bad record in the file.  One thing you can take a look at is this page - https://kluster.readthedocs.io/en/latest/requirements/index.html#reson-s7k.  Just to see if the file was logged with records that are going to work with Kluster. S7k can kind of be anything, unfortunately.

Another thing we could try is the File Analyzer in Kluster (Tools - File Analyzer).  Particularly the Kluster read test, which should show up for S7K.  That or the first_fifty_records test might shed some insight.  

Otherwise, you might need to share a file that we can look at.

**Comment by KevinKW87** [comment]
I think you may be right, the .s7k files seem to be missing respective SVPs and positioning information. 

Those look to be stored in separate files, which don't match up to the .s7k file. The file structure for this dataset has a "raw" and "supporting" set of files.

Here is the link to a sample file from the data set with the corresponding positioning and SVPs: 
https://drive.google.com/drive/folders/1SxkkdIU0_Cd5vMnRf50llvrYz9tbsayj?usp=drive_link

[3BN06-00355_first_fifty_records.txt](https://github.com/noaa-ocs-hydrography/kluster/files/14033461/3BN06-00355_first_fifty_records.txt)
[3BN06-00355_kluster_read_test.txt](https://github.com/noaa-ocs-hydrography/kluster/files/14033462/3BN06-00355_kluster_read_test.txt)

**Comment by ericgyounkin** [comment]
The s7k file has positioning, the POS file you have is a secondary source that wouldn't necessarily be needed.  The s7k file also has surface sound velocity, but lacks a sound velocity profile, which would be those svp files you have.  So the files that you have are fairly standard.

The problem here appears to be that you have 1016 records (attitude) logged without heading.  Which I would have thought violates the s7k 1016 datagram standard.  S7k has been around for a while, so I can say for certain what is possible with that file format.  I also haven't looked at this driver in ages.  Is this an older survey?

Not a whole lot I can do here with Kluster if there isn't heading.  If this isn't older data, maybe there is some new record that has attitude info.

**Comment by ericgyounkin** [comment]
I thought about this a little more, and remembered you can also provide heading with the separate 1013 record.  But that isn't in here either, so as far as I can tell, there is no heading in this file.  

I'm guessing maybe something like MBSystem lets you import the multibeam data and then replace the heading with the POS file after the fact.  You can kind of do that in Kluster, but our initial conversion step depends on the existence of heading, so theres not too much to do here.

**Comment by KevinKW87** [comment]
Hi Eric, I appreciate the help in trying to figure this out. I'll see what I can do in MB System.

**Comment by KevinKW87** [comment]
Closing Issue
